language: node_js
node_js:
  - "node"

cache: yarn

script: yarn run build

deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: gh-pages
